#!/usr/bin/env python3
"""
Script to generate Credits.ini file with Git repository contributors
"""

import subprocess
import sys
from collections import OrderedDict

def get_git_contributors():
    """Gets unique contributors list from Git repository"""
    try:
        # Execute git log to get all authors
        result = subprocess.run([
            'git', 'log', '--format=%an', '--all'
        ], capture_output=True, text=True, check=True)

        # Remove duplicates while maintaining order
        contributors = list(OrderedDict.fromkeys(result.stdout.strip().split('\n')))

        # Remove empty entries
        contributors = [c.strip() for c in contributors if c.strip()]

        # Filter very generic names or automation
        filtered_contributors = []
        skip_patterns = ['github-actions', 'bot', 'automated', 'ci', 'build']

        for contributor in contributors:
            skip = False
            for pattern in skip_patterns:
                if pattern.lower() in contributor.lower():
                    skip = True
                    break
            if not skip:
                filtered_contributors.append(contributor)

        return filtered_contributors

    except subprocess.CalledProcessError as e:
        print(f"Error executing git log: {e}", file=sys.stderr)
        return []
    except FileNotFoundError:
        print("Git not found in PATH", file=sys.stderr)
        return []

def generate_credits_ini(contributors):
    """Generates Credits.ini file content"""

    content = """;;; Credits.ini - Automatically Generated Credits File
;;; This file is automatically generated during the build process

[Credits]
ScrollRate = 2
ScrollRateEveryFrames = 2
ScrollDown = true
TitleColor = 255 255 255 255
MinorTitleColor = 200 200 255 255
NormalColor = 180 180 180 255

;;; Main Title
Style = TITLE
Text = "TheSuperHackers Team"

Style = NORMAL
Text = "- build by github.com/fbraz3"

;;; Blank line
Blank =

;;; Subtitle
Style = MINORTITLE
Text = "Developed by:"

;;; Blank line
Blank =

"""

    # Add each contributor
    for contributor in contributors:
        content += f""";;; Contributor: {contributor}
Style = NORMAL
Text = "{contributor}"

"""

    # Add final section
    content += """;;; Final blank line
Blank =

;;; Thank you message
Style = MINORTITLE
Text = "Thank you for playing!"

Blank =
Blank =
Blank =
"""

    return content

def main():
    """Main function"""
    print("Generating Credits.ini file...")

    # Get contributors list
    contributors = get_git_contributors()

    if not contributors:
        print("No contributors found. Using default list.")
        contributors = ["TheSuperHackers Team"]

    print(f"Found {len(contributors)} contributors:")
    for contributor in contributors:
        print(f"  - {contributor}")

    # Generate file content
    credits_content = generate_credits_ini(contributors)

    # Write file
    output_file = "Credits.ini"
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(credits_content)
        print(f"\n{output_file} file generated successfully!")
        return 0
    except Exception as e:
        print(f"Error writing {output_file} file: {e}", file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())
